/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

 import React, { Component } from 'react';
 import { Platform, StyleSheet, Text, View, Button } from 'react-native';
 import Runevm from 'react-native-runevm';
 import base64 from 'react-native-base64'

 export default class App extends Component<{}> {
   state = {
     status: 'starting',
     message: '--'
   };
   componentDidMount() {
    
    getRune();
   };

   async runRune() {
    const bytes = new Uint8Array(224*224*3);
    const b64encoded = base64.encodeFromByteArray(bytes);
    let message = await Runevm.runRune(b64encoded,[224*224*3], (message) => {
      console.log(">"+message);
     
      
    });
   }

   render() {
     return (
       <View style={styles.container}>
         <Text style={styles.welcome}>☆Runevm example☆</Text>
         <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
         <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
         <Text style={styles.instructions}>{this.state.message}</Text>
         <Button onPress={this.runRune} title="Run" color="#841584"/>
       </View>
     );
   }
 }

 
 
 async function getRune() {
  try {
    const runeURL = "https://rune-registry.web.app/registry/hotg-ai/inception_v1/app.rune";
    const bytes = new Uint8Array(await getBytes(runeURL));
    console.log("bytes.byteLength",bytes.byteLength);
    

 
    const b64encoded = base64.encodeFromByteArray(bytes);
    let message = await Runevm.loadWasm(b64encoded, (message) => {
      console.log(">"+message);
     
      
    });
 


  } catch (error) {
    console.error(error);
  }
};

function getBytes(url) {
  return new Promise((accept, reject) => {
      var req = new XMLHttpRequest();
      req.open("GET", url, true);
      req.responseType = "arraybuffer";

      req.onload = function(event) {
          var resp = req.response;
          if(resp) {
              accept(resp);
          }
      };

      req.send(null);
  });
}
 const styles = StyleSheet.create({
   container: {
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: '#F5FCFF',
   },
   welcome: {
     fontSize: 20,
     textAlign: 'center',
     margin: 10,
   },
   instructions: {
     textAlign: 'center',
     color: '#333333',
     marginBottom: 5,
   },
 });
 